SiteTitle: nullforce
SiteDescription: Stuff that interests me
Copyright: Copyright Â© 2022-2025 nullforce. All rights reserved.

GenerateSearchIndex: true
LinksUseHttps: true
Image: ./images/site-image.png

GitHubOwner: nullforce
GitHubName: nullforce.github.io
GitHubToken: '=> Config.FromSetting<string>("GITHUB_TOKEN")'
